version: '2'

volumes:
  postgres_test_data: {}

services:

  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile-tox
    environment:
      - DATABASE_URL=postgres://usertest:passwordtest@postgres/databasetest
      - ALLOWED_HOSTS=*
      - DEBUG=true
    depends_on:
      - postgres
    command: >-
      /bin/bash -c "
      /app/wait-for.sh postgres:5432 --timeout=60 &&
      cd /app/src/ &&
      tox"

  postgres:
    image: postgres:latest
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=usertest
      - POSTGRES_PASSWORD=passwordtest
      - POSTGRES_DB=databasetest