version: '2'

volumes:
  postgres_data_prod: {}

services:

  nginx:
    build:
      context: ../..
      dockerfile: docker/Dockerfile-nginx
    ports:
      - 0.0.0.0:8000:80
    depends_on:
      - app
    restart: always

  app:
    build:
      context: ../..
      dockerfile: docker/Dockerfile-app
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=*
      - DEBUG=false
    depends_on:
      - postgres
    restart: always
    command: >-
      /bin/bash -c "
      /app/wait-for.sh postgres:5432 --timeout=60 &&
      cd /app/src/ &&
      python manage.py migrate &&
      gunicorn -c gunicorn.conf.py wsgi"

  postgres:
    image: postgres:latest
    restart: always
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}